# Generated by Django 3.0.7 on 2020-06-03 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название группы')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation', models.TextField(verbose_name='Перевод')),
            ],
            options={
                'verbose_name': 'Перево',
                'verbose_name_plural': 'Переводы',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date_time', models.DateTimeField(auto_created=True, verbose_name='Дата создания')),
                ('word', models.CharField(max_length=150, verbose_name='Слово')),
                ('knowledge_level', models.PositiveSmallIntegerField(verbose_name='Уровень знания слова')),
                ('popularity', models.PositiveSmallIntegerField(verbose_name='Популярность слова')),
                ('groups', models.ManyToManyField(to='dictionarysite.Group', verbose_name='Группы')),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionarysite.Translation', verbose_name='Перевод')),
            ],
            options={
                'verbose_name': 'Слово',
                'verbose_name_plural': 'Слова',
            },
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date_time', models.DateTimeField(auto_created=True, verbose_name='Дата создания')),
                ('phrase', models.TextField(verbose_name='Фраза')),
                ('knowledge_level', models.PositiveSmallIntegerField(verbose_name='Уровень знания фразы')),
                ('groups', models.ManyToManyField(to='dictionarysite.Group', verbose_name='Группы')),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionarysite.Translation', verbose_name='Перевод')),
            ],
            options={
                'verbose_name': 'Фраза',
                'verbose_name_plural': 'Фразы',
            },
        ),
    ]
