# Generated by Django 3.0.7 on 2020-06-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionarysite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phrase',
            name='translation',
        ),
        migrations.RemoveField(
            model_name='word',
            name='translation',
        ),
        migrations.AddField(
            model_name='phrase',
            name='translations',
            field=models.ManyToManyField(to='dictionarysite.Translation', verbose_name='Перевод'),
        ),
        migrations.AddField(
            model_name='word',
            name='translations',
            field=models.ManyToManyField(to='dictionarysite.Translation', verbose_name='Перевод'),
        ),
    ]
