# Generated by Django 3.0.7 on 2020-06-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionarysite', '0002_auto_20200603_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrase',
            name='creation_date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='word',
            name='creation_date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
