# Generated by Django 3.0.7 on 2020-06-03 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionarysite', '0003_auto_20200603_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhraseTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation', models.CharField(max_length=150, verbose_name='Перевод')),
            ],
            options={
                'verbose_name': 'Перевод фразы',
                'verbose_name_plural': 'Переводы фраз',
            },
        ),
        migrations.CreateModel(
            name='WordTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation', models.CharField(max_length=150, verbose_name='Перевод')),
            ],
            options={
                'verbose_name': 'Перевод слова',
                'verbose_name_plural': 'Переводы слов',
            },
        ),
        migrations.RemoveField(
            model_name='phrase',
            name='translations',
        ),
        migrations.RemoveField(
            model_name='word',
            name='translations',
        ),
        migrations.DeleteModel(
            name='Translation',
        ),
        migrations.AddField(
            model_name='wordtranslation',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionarysite.Word', verbose_name='Слово'),
        ),
        migrations.AddField(
            model_name='phrasetranslation',
            name='phrase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionarysite.Phrase', verbose_name='Фраза'),
        ),
    ]
