# Generated by Django 3.0.7 on 2020-06-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionarysite', '0006_auto_20200603_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, to='dictionarysite.Group', verbose_name='Группы'),
        ),
        migrations.AlterField(
            model_name='word',
            name='knowledge_level',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Уровень знания'),
        ),
        migrations.AlterField(
            model_name='word',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Заметки'),
        ),
        migrations.AlterField(
            model_name='word',
            name='popularity',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Популярность слова'),
        ),
        migrations.AlterField(
            model_name='word',
            name='translation',
            field=models.ManyToManyField(blank=True, null=True, related_name='_word_translation_+', to='dictionarysite.Word', verbose_name='Перевод'),
        ),
    ]
