# Generated by Django 3.0.7 on 2020-06-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionarysite', '0007_auto_20200603_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='is_translation',
            field=models.BooleanField(default=True, verbose_name='Английское слово'),
        ),
    ]
