# Generated by Django 3.0.7 on 2020-06-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionarysite', '0008_word_is_translation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='popularity',
            new_name='rank',
        ),
        migrations.RemoveField(
            model_name='word',
            name='knowledge_level',
        ),
        migrations.AddField(
            model_name='word',
            name='priority',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Приоритет изучения'),
        ),
    ]
