# Generated by Django 3.0.7 on 2020-06-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionarysite', '0010_auto_20200604_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='priority',
            field=models.PositiveSmallIntegerField(blank=True, default=10, null=True, verbose_name='Приоритет изучения'),
        ),
        migrations.AlterField(
            model_name='word',
            name='rank',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Популярность слова'),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.TextField(db_index=True, unique=True, verbose_name='Слово'),
        ),
    ]
