# Generated by Django 3.0.7 on 2020-06-06 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionarysite', '0012_word_is_not_display'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='word',
            name='is_translation',
        ),
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
        migrations.AddField(
            model_name='group',
            name='words',
            field=models.ManyToManyField(blank=True, null=True, to='dictionarysite.Word', verbose_name='Слова'),
        ),
        migrations.RemoveField(
            model_name='word',
            name='translation',
        ),
        migrations.AddField(
            model_name='word',
            name='translation',
            field=models.TextField(blank=True, null=True, verbose_name='Перевод'),
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Язык')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionarysite.Word', verbose_name='Язык')),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки',
            },
        ),
    ]
