# Generated by Django 3.0.7 on 2020-06-06 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionarysite', '0013_auto_20200606_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='words',
        ),
        migrations.RemoveField(
            model_name='language',
            name='word',
        ),
        migrations.AddField(
            model_name='word',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, to='dictionarysite.Group', verbose_name='Группы'),
        ),
        migrations.AddField(
            model_name='word',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionarysite.Language', verbose_name='Язык'),
        ),
    ]
