# Generated by Django 3.0.7 on 2020-06-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionarysite', '0016_auto_20200612_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Язык'),
        ),
    ]
