# Generated by Django 3.0.7 on 2020-06-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionarysite', '0018_auto_20200612_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='translation',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Перевод'),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(db_index=True, max_length=250, verbose_name='Слово'),
        ),
    ]
