# Generated by Django 3.0.7 on 2020-06-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionarysite', '0019_auto_20200618_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='groups',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='dictionarysite.Group', verbose_name='Группы'),
        ),
    ]
