# Generated by Django 3.0.7 on 2020-08-18 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionarysite', '0020_auto_20200618_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='language',
            field=models.ForeignKey(blank=True, default=9, on_delete=django.db.models.deletion.CASCADE, to='dictionarysite.Language', verbose_name='Язык'),
            preserve_default=False,
        ),
    ]
