# Generated by Django 3.0.7 on 2020-08-18 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionarysite', '0021_auto_20200818_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionarysite.Language', verbose_name='Язык'),
        ),
    ]
